---
- hosts: all  
  roles:
    - role: riponbanik.foreman
      foreman_hostname: foreman.vagrantup.com
      foreman_version: 1.19      
      foreman_plugins: 
        - docker
      puppet_options:
          autosign-entries: '*'
      
