---
driver:
  name: ec2
  #aws_ssh_key_id: kp-infra-nprd
  security_group_ids: ["sg-22a6d25b"]
  region: ap-southeast-2
  availability_zone: b
  subnet_id: subnet-47cecb23
  iam_profile_name: profile-ec2-default
  instance_type: t3.small
  associate_public_ip: true
  interface: private
  tags:
    Project: Infrastructure
    CostCenter: Quan Tran

transport:
  #ssh_key: /path/to/id_rsa-aws
  connection_timeout: 10
  connection_retries: 60

platforms:
  - name: windows-2012r2    
    transport:
      name: winrm
      username: administrator       
      #ssh_key: 'C:\Users\riponb\Documents\AWS\key\kp-infra-nprd.pem'
    driver:
      image_id: ami-06503cc958e650ee1
      private_ip_address: '10.50.2.218' 
      retryable_tries: 60
      retryable_sleep: 10     
     
  - name: amazon-20180810
    lifecycle:
      pre_converge:
        - remote: sudo yum -y install python-pip
        - remote: sudo pip install pywinrm
    driver:
      image_id: ami-09c4c37cdfdc4222c
      private_ip_address: '10.50.2.217'  
    transport:
      username: ec2-user 
      #ssh_key: 'C:\Users\riponb\Documents\AWS\key\kp-infra-nprd.pem'  
      max_ssh_sessions: 1
    provisioner:
        name: ansible_playbook      
        roles_path: ../
        role_name: kitchen_test_role
        modules_path: lib/windows      
        require_ansible_repo: false            
        ansible_verbose: true
        ansible_version: latest  
        ansible_connection: winrm
        ansible_inventory: inventory/hosts
        ansible_host_key_checking: false
        ansible_diff: true
        ansible_verbosity: 4
        playbook: playbook.yml
        require_windows_support: true
        require_chef_for_busser: false      
    verifier:
      name: shell
      command: echo 'Skipping Verify'  
    suites:
     - name: ansible
       driver_config:
         hostname: '10.50.2.217'  

suites:
  - name: default

  