driver:
  name: vagrant
  provider: hyperv
  differencing_disk: true
  network:
  - ["public_network", bridge: "Default Switch"]

platforms:
  - name: testhost
    driver_plugin: vagrant
    driver_config:
      box: centos/7      
    transport:
      max_ssh_sessions: 1
    provisioner:
      name: ansible_playbook
      roles_path: ../
      role_name: kitchen_test_role
      ansible_connection: local   
      ansible_inventory: inventory/hosts   
      require_windows_support: true
      require_chef_for_busser: false
      ansible_host_key_checking: false
      ansible_verbose: true
      ansible_verbosity: 4
      playbook: playbook.yml
    verifier:
      name: shell
      command: echo 'Skipping Verify'  
  
suites:
  - name: default