---
# Set facts
- name: Specify base or custom install
  set_fact:
    base_only: false 
  when: (install_puppet_master | bool)

# Include variables and define needed variables.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

# Setup/install tasks.
- include_tasks: "Setup_{{ ansible_os_family }}.yml"  