---
- name: set hostname as fqdn
  hostname: name={{ foreman_hostname }}
  when: foreman_hostname is defined

- name: copy script to modify /etc/hosts
  copy:
    src: mungehosts
    dest: /usr/local/bin/mungehosts
    mode: 0755  

- name: resolve hostname via /etc/hosts to resolve `hostname -f`
  #lineinfile: dest=/etc/hosts line="{{ansible_default_ipv4.address}} {{ansible_fqdn}} {{ansible_hostname}}"   
  #command: python /tmp/modify_hosts.py "{{ansible_default_ipv4.address}}", "{{ansible_default_ipv4.address}} {{ansible_hostname}}"
  command: /usr/local/bin/mungehosts -a "{{ansible_default_ipv4.address}} {{foreman_hostname}}"
  when: foreman_hostname is defined

- name: Update CA Certificate  
  apt:
    name: install ca-certificates
    update_cache: yes

- name: Install Puppet Repository
  apt:
    deb: https://apt.puppetlabs.com/{{puppet_version}}-release-{{ansible_distribution_release}}.deb

- name: Install Foreman Repository
  block:
    - name: Install Foerman Repo     
      apt_repository:
        repo: deb http://deb.theforeman.org/ {{ansible_distribution_release}} {{foreman_version}}
        state: present
        filename: /etc/apt/sources.list.d/foreman.list
    - name: Install Foerman Plugin Repo     
      apt_repository:
        repo: deb http://deb.theforeman.org/ plugins {{foreman_version}}
        state: present
        filename: /etc/apt/sources.list.d/foreman_plugins.list    
    - name: Add Public Key      
      apt_key:
        url: https://deb.theforeman.org/pubkey.gpg
        state: present     




